sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: yf0PfudfmirSUpbVpK+6SpL+mxMJU9TRfy7Vy6tEtVshTQyv5eXYtn/WnlJadci2DQyMpqwdxf7tWYP7X9qrz9+9iqs9OStOiHFCy/w8NhV0dCIpRuIpzAUG6/h4DqRdmOjJmxM8Pz2mtPEVbllnrT6CPh6V2ZXh0gYgi4yQL9gjOw4mkgf8h5WKPULalWFmWNnpO7drp92XfL5y+KSdG3xAIGT7b5ms/3Jjf4rf3blBdnVOuvkctJLWM6LYujDXigXcGLT6XJPpK0MWLGq9jjtcuMLzuUxGovCfwqlKtJm45vREkpIbmGUTeUBudQ8jZmhAt5F+KTrtxArWGPz4dPkwc8eKLtSQLDevCUNNqNZ9W3amxtD9GdhVz45XZCaMsolNf4WLi7ZsPZfeNG3oJ0fBpNWl0LtaRnO1l6rz3Hsbe+08aSc6ItsZ0RGFFAdBWk4nCguWyu+saeziirtH/KwUIOP0Hwx9eRDhJEE9o/o8Z1oE7HdSxsWTgydWlgCXckomw7Iotmn0XIPaFoA1ofoG1dZWoUX8YyibXx+sI9mkByV5XgfnSakUJeCqPXq9tcbkELqeWGH3QqfUHBIbwJDiJ7SyUpBgFMAMJR9sP5Z2SKSHFN0ltuuVNBlpoVjVNQ6WkuGSDrcR6cWG9T46s/R6LuXTxnoKf+kKQ7zgDIc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Word-Only-a-Word-Volume-02_5573
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy